/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.Adresa;
import domen.Mesto;
import domen.Student;
import java.io.IOException;
import java.lang.reflect.Method;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import komunikacija.Komunikacija;
import tableModel.StudentTableModel;
import transfer.TObjekat;

/**
 *
 * @author user
 */
public class FNovi extends javax.swing.JFrame {

    JTable tabela;
    Student s1 = new Student();

    /**
     * Creates new form FNovi
     */
    public FNovi(JTable tab) {
        initComponents();

        srediFormu();
        try {
            Student s = (Student) Komunikacija.vratiObjekat().getHashMapa().get("sk");
            txtBrIndeksa.setText(s.getBrIndeksa());
            txtBroj.setText(s.getAdresa().getBroj());
            txtIme.setText(s.getIme());
            txtJMBG.setText(String.valueOf(s.getJMBG()));
            txtPrezime.setText(s.getPrezime());
            txtUlica.setText(s.getAdresa().getUlica());
            comboMesto.setSelectedItem(s.getAdresa().getMesto());
            jbtnKreiraj.setEnabled(false);
            jbtnIzmeni.setEnabled(true);
            String JMBGtext = txtJMBG.getText().trim();
            s1.setJMBG(Integer.parseInt(JMBGtext));
            tabela = tab;
        } catch (Exception ex) {
            jbtnKreiraj.setEnabled(true);
            jbtnIzmeni.setEnabled(false);
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtUlica = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBroj = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboMesto = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBrIndeksa = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtnKreiraj = new javax.swing.JButton();
        jbtnPonisti = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adresa"));

        jLabel5.setText("Ulica");

        jLabel6.setText("Broj");

        txtBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojActionPerformed(evt);
            }
        });

        jLabel8.setText("Mesto");

        comboMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBroj)
                            .addComponent(comboMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(txtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setText("JMBG");

        jLabel4.setText("Broj indeksa");

        jLabel2.setText("Prezime");

        jLabel1.setText("Ime");

        jbtnKreiraj.setText("Kreiraj");
        jbtnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajActionPerformed(evt);
            }
        });

        jbtnPonisti.setText("Ponisti");
        jbtnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPonistiActionPerformed(evt);
            }
        });

        jbtnIzmeni.setText("Izmeni");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jbtnKreiraj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jbtnIzmeni)
                .addGap(18, 18, 18)
                .addComponent(jbtnPonisti)
                .addGap(87, 87, 87))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtJMBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBrIndeksa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnKreiraj)
                    .addComponent(jbtnPonisti)
                    .addComponent(jbtnIzmeni))
                .addGap(51, 51, 51))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtBrIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojActionPerformed

    private void jbtnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPonistiActionPerformed
        txtIme.setText(null);
        txtPrezime.setText(null);
        txtJMBG.setText(null);
        txtBrIndeksa.setText(null);
        txtUlica.setText(null);
        txtBroj.setText(null);
    }//GEN-LAST:event_jbtnPonistiActionPerformed

    private void jbtnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajActionPerformed
        try {

            String ime = txtIme.getText().trim();
            String prezime = txtPrezime.getText().trim();
            String JMBGtext = txtJMBG.getText().trim();
            int JMBG = Integer.parseInt(JMBGtext);
            String brIndeksa = txtBrIndeksa.getText().trim();
            String ulica = txtUlica.getText().trim();
            String broj = txtBroj.getText().trim();
            Mesto mesto = (Mesto) comboMesto.getSelectedItem();
            if (validacija()) {
                Student s = new Student(ime, prezime, brIndeksa, JMBG, new Adresa(ulica, broj, mesto));
                TObjekat posalji = new TObjekat(s, "student");
                Komunikacija.vratiObjekat().posalji(posalji);
                TObjekat odgovor = Komunikacija.vratiObjekat().procitaj();
                if (odgovor.getPoruka().equals("ok")) {
                    JOptionPane.showMessageDialog(this, "Student je snimljen");
                    jbtnPonistiActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Student nije snimljen");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Unesite sve podatke");
            }
            Student s4= new Student();
            s4.setIme("perica aolhfinsaodfhbnaslofihasbfdloisufhdasklhfinb");
            Class metaX = Student.class;
            System.out.println("informacije o klasi Racun");
            System.out.println("************************");
            System.out.println("naziv klase:" + metaX.getName());
            Method[] metode = metaX.getDeclaredMethods();
            System.out.println("************************");
            System.out.println("metode klase:");
            for (int i = 0; i < metode.length; i++) {
                System.out.println(metode[i]);
                if(metode[i].getName().equals("getIme")){
                    System.out.println(metode[i].invoke(s4, null));
                }
            }
            System.out.println("************************");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbtnKreirajActionPerformed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
        try {
            String ime = txtIme.getText().trim();
            String prezime = txtPrezime.getText().trim();
            String JMBGtext = txtJMBG.getText().trim();
            int JMBG = Integer.parseInt(JMBGtext);
            String brIndeksa = txtBrIndeksa.getText().trim();
            String ulica = txtUlica.getText().trim();
            String broj = txtBroj.getText().trim();
            Mesto mesto = (Mesto) comboMesto.getSelectedItem();
            if (validacija()) {
                Student s = new Student(ime, prezime, brIndeksa, JMBG, new Adresa(ulica, broj, mesto));
                TObjekat posalji = new TObjekat(s1, "studentIzmeni");
                Komunikacija.vratiObjekat().posalji(posalji);
                TObjekat posalji1 = new TObjekat(s, null);
                Komunikacija.vratiObjekat().posalji(posalji1);
                TObjekat odgovor = Komunikacija.vratiObjekat().procitaj();
                if (odgovor.getPoruka().equals("ok")) {
                    JOptionPane.showMessageDialog(this, "Izmene su sacuvane");
                    StudentTableModel stm = (StudentTableModel) tabela.getModel();
                    Student stud = new Student();
                    TObjekat posalji6 = new TObjekat(stud, "vratiSveStudente");
                    Komunikacija.vratiObjekat().posalji(posalji6);
                    List<Student> listaStudenata = (List<Student>) Komunikacija.vratiObjekat().procitaj().getObjekat();
                    stm.setListaStudenata(listaStudenata);
                    stm.fireTableDataChanged();
                } else {
                    JOptionPane.showMessageDialog(this, "Doslo je do greske, izmene nisu sacuvane");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Unesite sve podatke");
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    public boolean validacija() {
        try {
            int a = Integer.parseInt(txtJMBG.getText());
            if (txtIme.getText().equals("") || txtPrezime.getText().equals("") || txtBrIndeksa.getText().equals("") || txtBroj.getText().equals("") || txtUlica.getText().equals("")) {
                return false;
            } else {
                return true;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            return false;

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FNovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FNovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FNovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FNovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FNovi(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnKreiraj;
    private javax.swing.JButton jbtnPonisti;
    private javax.swing.JTextField txtBrIndeksa;
    private javax.swing.JTextField txtBroj;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtUlica;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            comboMesto.removeAllItems();
            Mesto m = new Mesto();
            TObjekat posalji = new TObjekat(m, "vratiMesta");
            Komunikacija.vratiObjekat().posalji(posalji);

            List<Mesto> lista = (List<Mesto>) Komunikacija.vratiObjekat().procitaj().getObjekat();

            for (Mesto mesto : lista) {
                comboMesto.addItem(mesto);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
