/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.Adresa;
import domen.DomenskiObjekat;
import domen.Mesto;
import domen.PolozenIspit;
import domen.Student;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import tableModel.StudentTableModel;
import transfer.TObjekat;

/**
 *
 * @author user
 */
public class FPretraga extends javax.swing.JFrame {

    /**
     * Creates new form FPretraga
     */
    public FPretraga() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();
        jbtnIspiti = new javax.swing.JButton();
        jbtnPrijavi = new javax.swing.JButton();
        comboMesto = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblTabela);

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime");

        jLabel3.setText("Mesto:");

        jLabel4.setText("JMBG");

        jButton1.setText("Pretraga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnIzmeni.setText("Izmeni");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });

        jbtnObrisi.setText("Obrisi");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        jbtnIspiti.setText("Prikazi polozene ispite");
        jbtnIspiti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIspitiActionPerformed(evt);
            }
        });

        jbtnPrijavi.setText("Prijavi ispite");
        jbtnPrijavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrijaviActionPerformed(evt);
            }
        });

        comboMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnIzmeni)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnObrisi)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnIspiti)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnPrijavi)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(comboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnIzmeni)
                    .addComponent(jbtnObrisi)
                    .addComponent(jbtnIspiti)
                    .addComponent(jbtnPrijavi))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
        try {
            StudentTableModel mtm = (StudentTableModel) jtblTabela.getModel();
            int a = jtblTabela.getSelectedRow();
            Student s = mtm.getListaStudenata().get(a);
            Komunikacija.vratiObjekat().getHashMapa().put("sk", s);
            
            JOptionPane.showMessageDialog(this, "Izmenite podatke o studentu");
            Komunikacija.vratiObjekat().getHashMapa().put("tabela", jtblTabela);
            FNovi novi = new FNovi(jtblTabela);
            novi.setVisible(true);
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        try {
            StudentTableModel mtm = (StudentTableModel) jtblTabela.getModel();
            int a = jtblTabela.getSelectedRow();
            Student s = mtm.getListaStudenata().get(a);
            TObjekat posalji = new TObjekat(s, "obrisi");
            Komunikacija.vratiObjekat().posalji(posalji);
            TObjekat odgovor = Komunikacija.vratiObjekat().procitaj();
            if (odgovor.getPoruka().equals("ok")) {
                JOptionPane.showMessageDialog(this, "Student je obisan");
                mtm.obrisiStudenta(a);
            } else {
                JOptionPane.showMessageDialog(this, "Student nije obisan");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnIspitiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIspitiActionPerformed
        try {
            StudentTableModel mtm = (StudentTableModel) jtblTabela.getModel();
            int a = jtblTabela.getSelectedRow();
            
            List<Student> lista = mtm.getListaStudenata();
            Student s = lista.get(a);
            TObjekat zahtev = new TObjekat(s, "polozeniIspiti");
            Komunikacija.vratiObjekat().posalji(zahtev);
            List<PolozenIspit> listaPolozenih = (List<PolozenIspit>) Komunikacija.vratiObjekat().procitaj().getObjekat();
            Komunikacija.vratiObjekat().getHashMapa().put("lista", listaPolozenih);
            FPolozeniIspiti polozeni = new FPolozeniIspiti();
            polozeni.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbtnIspitiActionPerformed

    private void jbtnPrijaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrijaviActionPerformed
        try {
//            StudentTableModel stm = (StudentTableModel) jtblTabela.getModel();
//            Student s = stm.getListaStudenata().get(jtblTabela.getSelectedRow());
            StudentTableModel mtm = (StudentTableModel) jtblTabela.getModel();
            int a = jtblTabela.getSelectedRow();
            List<Student> lista = mtm.getListaStudenata();
            Student s = lista.get(a);
            Komunikacija.vratiObjekat().getHashMapa().put("student", s);
            FPrijaviIspite prijavi = new FPrijaviIspite();
            prijavi.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbtnPrijaviActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String ime = txtIme.getText();
            String prezime = txtPrezime.getText();
            int jmbg;
            if(txtJMBG.getText().equals("")){
                jmbg =0;
            }else{
                jmbg = Integer.parseInt(txtJMBG.getText());
            }
            Mesto m = (Mesto) comboMesto.getSelectedItem();
            Student s = new Student();
            s.setIme(ime);
            s.setJMBG(jmbg);
            s.setPrezime(prezime);
            Adresa a = new Adresa();
            a.setMesto(m);
            s.setAdresa(a);
            TObjekat posalji = new TObjekat(s, "nadji");
            Komunikacija.vratiObjekat().posalji(posalji);
            TObjekat odgovor = Komunikacija.vratiObjekat().procitaj();
            List<Student> lista = (List<Student>) odgovor.getObjekat();
            if (lista.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe studenta prema zadatim vrednostima.");
            }
            StudentTableModel stm = new StudentTableModel(lista);
            jtblTabela.setModel(stm);
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Doslo je do greske, proverite podatke i pokusajte ponovo");
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPretraga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPretraga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPretraga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPretraga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPretraga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboMesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnIspiti;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnPrijavi;
    private javax.swing.JTable jtblTabela;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            Student s = new Student();
            TObjekat posalji = new TObjekat(s, "vratiSveStudente");
            Komunikacija.vratiObjekat().posalji(posalji);

            List<Student> listaStudenata = (List<Student>) Komunikacija.vratiObjekat().procitaj().getObjekat();
            StudentTableModel mtm = new StudentTableModel(listaStudenata);
            jtblTabela.setModel(mtm);

            comboMesto.removeAllItems();

            Mesto m = new Mesto();
            TObjekat posalji2 = new TObjekat(m, "vratiMesta");
            Komunikacija.vratiObjekat().posalji(posalji2);

            List<Mesto> lista = (List<Mesto>) Komunikacija.vratiObjekat().procitaj().getObjekat();

            for (Mesto mesto : lista) {
                comboMesto.addItem(mesto);
            }
            Mesto nepoznato = null;
            comboMesto.addItem(nepoznato);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
