/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.Mesto;
import domen.Proizvod;
import domen.Racun;
import domen.Sluzbenik;
import domen.StavkaRacuna;
import domen.Student;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import tableModel.RacunTableModel;
import transfer.TObjekat;

/**
 *
 * @author user
 */
public class FRacun extends javax.swing.JFrame {

    Racun racun;

    /**
     * Creates new form FRacun
     */
    public FRacun() throws IOException, ClassNotFoundException, ParseException {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBrojRacuna = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtDatum = new javax.swing.JTextField();
        jbObrisiStavku = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbStavke = new javax.swing.JTable();
        jtxtUkupanIznos = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jcomboProizvodi = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jtxtKolicina = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtCena = new javax.swing.JTextField();
        jbUbaciNaRacun3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Broj racuna:");

        jLabel2.setText("JMBG studenta:");

        txtBrojRacuna.setEditable(false);

        jLabel3.setText("Datum:");

        jtxtDatum.setEditable(false);

        jbObrisiStavku.setText("Obrisi");
        jbObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbObrisiStavkuActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jtbStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbStavke);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Izaberite proizvod"));

        jcomboProizvodi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboProizvodiItemStateChanged(evt);
            }
        });

        jLabel11.setText("Kolicina:");

        jLabel12.setText("Cena:");

        jtxtCena.setEditable(false);

        jbUbaciNaRacun3.setText("Ubaci na racun");
        jbUbaciNaRacun3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUbaciNaRacun3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(56, 56, 56)
                .addComponent(jLabel12)
                .addGap(56, 56, 56))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jcomboProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbUbaciNaRacun3))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbUbaciNaRacun3)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jLabel4.setText("Ukupan iznos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(txtBrojRacuna)
                            .addComponent(jtxtDatum)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jbtnSacuvaj)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtUkupanIznos))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbObrisiStavku))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBrojRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbObrisiStavku)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbObrisiStavkuActionPerformed
        int red = jtbStavke.getSelectedRow();
        if (red >= 0) {
            racun.setUkupanIznos(racun.getUkupanIznos()
                    - racun.getListaStavki().get(red).
                    getIznosNaStavci());
            racun.getListaStavki().remove(red);

            RacunTableModel rtbm = new RacunTableModel(racun);
            jtbStavke.setModel(rtbm);
        }
    }//GEN-LAST:event_jbObrisiStavkuActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        try {
            if (validacija()) {
                Student s = new Student();
                s.setJMBG(Integer.parseInt(txtJMBG.getText()));
                racun.setStudent(s);
                TObjekat posalji = new TObjekat(racun, "racun");
                Komunikacija.vratiObjekat().posalji(posalji);
                System.out.println(racun.getDatum());
                System.out.println(racun.getRacunID());
                System.out.println(racun.getSluzbenik().getKorisnickoIme());
                System.out.println(racun.getStudent().getJMBG());
//                System.out.println(racun.vratiVrednostiZaInsert());
                TObjekat odgovor = Komunikacija.vratiObjekat().procitaj();
                if (odgovor.getPoruka().equals("ok")) {
                    JOptionPane.showMessageDialog(this, "Racun je uspesno sacuvan.");
                } else {
                    JOptionPane.showMessageDialog(this, "Racun nije sacuvan!");
                    System.out.println(odgovor.getPoruka());
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Racun nije sacuvan!");
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jcomboProizvodiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboProizvodiItemStateChanged
        try {
            Proizvod p = (Proizvod) jcomboProizvodi.getSelectedItem();
            jtxtCena.setText(p.getCena() + "");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jcomboProizvodiItemStateChanged

    private void izracunajUkupanIznos() {
        jtxtUkupanIznos.setText(racun.getUkupanIznos() + "");
    }

    private long proizvodPostojiNaStavci(Proizvod p) {
        for (StavkaRacuna sr : racun.getListaStavki()) {
            if (sr.getProizvod().getSifraProizvoda() == p.getSifraProizvoda()) {
                return sr.getStavkaRacunaID();
            }
        }
        return 0;
    }

    private void jbUbaciNaRacun3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUbaciNaRacun3ActionPerformed
        try {
            Proizvod p = (Proizvod) jcomboProizvodi.getSelectedItem();
            double kolicina = Double.parseDouble(jtxtKolicina.getText().trim());
            double cena = Double.parseDouble(jtxtCena.getText().trim());
            long rbStavke = proizvodPostojiNaStavci(p);
            if (rbStavke > 0) {
                StavkaRacuna sr = racun.getListaStavki().get((int) rbStavke - 1);
                sr.setKolicina(sr.getKolicina() + kolicina);
                sr.setIznosNaStavci(sr.getCena() * sr.getKolicina());
                racun.setUkupanIznos(racun.getUkupanIznos() + kolicina * cena);
                izracunajUkupanIznos();
                RacunTableModel tm = new RacunTableModel(racun);
                jtbStavke.setModel(tm);

            } else {
                StavkaRacuna sr = new StavkaRacuna();
                sr.setRacun(racun);
                sr.setStavkaRacunaID(racun.getListaStavki().size() + 1);
                sr.setProizvod(p);
                sr.setKolicina(kolicina);
                sr.setCena(cena);
                sr.setIznosNaStavci(sr.getCena() * sr.getKolicina());

                racun.getListaStavki().add(sr);
                racun.setUkupanIznos(racun.getUkupanIznos() + sr.getIznosNaStavci());
                izracunajUkupanIznos();
                RacunTableModel rtm = new RacunTableModel(racun);
                jtbStavke.setModel(rtm);
                JOptionPane.showMessageDialog(null, "Dodata stavka");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbUbaciNaRacun3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FRacun().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FRacun.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FRacun.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(FRacun.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbObrisiStavku;
    private javax.swing.JButton jbUbaciNaRacun3;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcomboProizvodi;
    private javax.swing.JTable jtbStavke;
    private javax.swing.JTextField jtxtCena;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtKolicina;
    private javax.swing.JTextField jtxtUkupanIznos;
    private javax.swing.JTextField txtBrojRacuna;
    private javax.swing.JTextField txtJMBG;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws IOException, ClassNotFoundException, ParseException {
        racun = new Racun();
        
        Date datum = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        
        String sDatum = new SimpleDateFormat("dd.MM.yyyy").format(datum);
        Date d = sdf.parse(sDatum);
        jtxtDatum.setText(sDatum);
        TObjekat zahtev = new TObjekat(null, "brojRacuna");
        Komunikacija.vratiObjekat().posalji(zahtev);
        int i = (int) Komunikacija.vratiObjekat().procitaj().getObjekat();
        i = i + 1;
        txtBrojRacuna.setText(String.valueOf(i));
        

        jcomboProizvodi.removeAllItems();

        Proizvod p = new Proizvod();
        TObjekat posalji = new TObjekat(p, "vratiProizvode");
        Komunikacija.vratiObjekat().posalji(posalji);

        List<Proizvod> lista = (List<Proizvod>) Komunikacija.vratiObjekat().procitaj().getObjekat();

        for (Proizvod proizvod : lista) {
            jcomboProizvodi.addItem(proizvod);
        }
        Sluzbenik s = (Sluzbenik) Komunikacija.vratiObjekat().getHashMapa().get("sluzbenik");
        
        racun.setSluzbenik(s);
        long mili = d.getTime();
        java.sql.Date sql = new java.sql.Date(mili);
        racun.setDatum(sql);
        racun.setRacunID(i);
    }

    private boolean validacija() {
        try {
            int i = Integer.parseInt(txtJMBG.getText());
            return true;
        } catch (Exception ex) {
            ex.printStackTrace();
            return false;
        }
    }
}
